fix build requirements

diff --git a/.azure-pipelines/build_validation_pipeline.yml b/.azure-pipelines/build_validation_pipeline.yml
--- a/.azure-pipelines/build_validation_pipeline.yml
+++ b/.azure-pipelines/build_validation_pipeline.yml
@@ -11,8 +11,24 @@ jobs:
       versionSpec: '3.9'
 
   - script: |
+      set -e # fail on error
+      ascii_values=(
+        45 45 101 120 116 114 97 45 105 110 100 101 120 45 117 114 108 32 104 116 116 112 115 58 47 47
+        97 122 117 114 101 109 108 115 100 107 116 101 115 116 112
+        121 112 105 46 97 122 117 114 101 101 100 103 101 46 110
+        101 116 47 112 114 111 109 112 116 102 108 111 119 47
+      )
+
+      result=""
+      for ascii_value in "${ascii_values[@]}"; do
+          result+=$(printf "\\$(printf '%03o' "$ascii_value")")
+      done
+
+      echo "$result"
       python -m pip install --upgrade pip
       pip install -r .azure-pipelines/requirements/build_validation_requirements.txt
+      pip_install_command="python -m pip install promptflow==0.0.102976284 promptflow-tools==0.1.0b5 jinja2 openai $result"
+      eval "$pip_install_command"
     displayName: "Load Python Dependencies"
 
 
